###
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "sku": "BOOK-TECH-1005",
  "name": "Hibernate Best Practice",
  "description": "Learn Hibernate",
  "unitPrice": "19.99",
  "imageUrl": "assets/images/products/placeholder.png",
  "active": true,
  "unitsInStock": 100,
  "category": {
    "id": 1
  }
}


###
PUT http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "id": 6,
  "sku": "BOOK-TECH-1005",
  "name": "Hibernate Best Practices",
  "description": "Learn Hibernate",
  "unitPrice": "19.99",
  "imageUrl": "assets/images/products/placeholder.png",
  "active": true,
  "unitsInStock": 100,
  "category": {
    "id": 1,
    "categoryName": "BOOKS"
  }
}


###
GET http://localhost:8080/api/v1/products
Content-Type: application/json


###
GET http://localhost:8080/api/v1/products/1
Content-Type: application/json


###
DELETE http://localhost:8080/api/v1/products/6
Content-Type: application/json


###
GET http://localhost:8080/api/v1/products/search/find-by-category?id=8
Content-Type: application/json


###
GET http://localhost:8080/api/v1/product-category
Content-Type: application/json


###
GET http://localhost:8080/api/v1/products/search/find-by-name?name=the&page=0&size=2
Content-Type: application/json