###
POST https://localhost:8443/api/v1/products
Content-Type: application/json

{
  "sku": "BOOK-TECH-1005",
  "name": "Hibernate Best Practice",
  "description": "Learn Hibernate",
  "unitPrice": "19.99",
  "imageUrl": "assets/images/products/placeholder.png",
  "active": true,
  "unitsInStock": 100,
  "category": {
    "id": 1
  }
}


###
PUT https://localhost:8443/api/v1/products
Content-Type: application/json

{
  "id": 6,
  "sku": "BOOK-TECH-1005",
  "name": "Hibernate Best Practices",
  "description": "Learn Hibernate",
  "unitPrice": "19.99",
  "imageUrl": "assets/images/products/placeholder.png",
  "active": true,
  "unitsInStock": 100,
  "category": {
    "id": 1,
    "categoryName": "BOOKS"
  }
}


###
GET https://localhost:8443/api/v1/products?page=0&size=10
Content-Type: application/json


###
GET https://localhost:8443/api/v1/products/1
Content-Type: application/json


###
DELETE https://localhost:8443/api/v1/products/6
Content-Type: application/json


###
GET https://localhost:8443/api/v1/products/search/find-by-category?id=8
Content-Type: application/json


###
GET https://localhost:8443/api/v1/product-category
Content-Type: application/json


###
GET https://localhost:8443/api/v1/products/search/find-by-name?name=the&page=0&size=2
Content-Type: application/json


###
GET https://localhost:8443/api/v1/countries
Content-Type: application/json


###
GET https://localhost:8443/api/v1/countries/1
Content-Type: application/json


###
POST https://localhost:8443/api/v1/checkout
Content-Type: application/json

{
  "customer":{
    "firstName":"Rahul",
    "lastName":"Choudhary",
    "email":"no-reply@test.com"
  },
  "shippingAddress":{
    "street":"Luxmanweg",
    "city":"Amsterdam",
    "state":"Amsterdam",
    "country":"Netherlands",
    "zipCode":"1672QA"
  },
  "billingAddress":{
    "street":"Luxmanweg",
    "city":"Amsterdam",
    "state":"Amsterdam",
    "country":"Netherlands",
    "zipCode":"1672QA"
  },
  "order":{
    "totalPrice":36.98,
    "totalQuantity":2
  },
  "orderItems":[
    {
      "imageUrl":"assets/images/products/coffeemugs/coffeemug-luv2code-1000.png",
      "quantity":1,
      "unitPrice":18.99,
      "product":{
        "id": 1
      }
    },
    {
      "imageUrl":"assets/images/products/mousepads/mousepad-luv2code-1000.png",
      "quantity":1,
      "unitPrice":17.99,
      "product":{
        "id": 2
      }
    }
  ]
}


###
GET https://localhost:8443/api/v1/orders/search?email=no-reply@test.com&page=0&size=20
Content-Type: application/json

###
GET https://localhost:8443/api/v1/orders/1
Content-Type: application/json